---
- name: Deploy IT24 Website on worker 1 webserver
  hosts: webservers
  become: yes

  tasks:
    - name: Update System packages
      yum: 
        name: '*'

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache Service
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Allow HTTP and HTTPS Through Firewall
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - http
        - https

    - name: Create Website Directory
      file: 
        path: /var/www/html/it24
        state: directory
    
    - name: Set Apache User and Group OwenerShip
      file:
        path: /var/www/html/it24
        owner: apache 
        group: apache
        recurse: yes

    - name: Test Apache Configuration
      command: apachectl configuration
      register: apache_config_test
      ignore_errors: yes
    
    - name: Restart Apache Service
      service: 
        name: httpd
        state: restarted
      when: apache_config_test.rc == 0

